title: Greerati.dev
tagline: LIFE, FAMILY, TRAVEL, REVIEW
description: บล็อกส่วนตัวเกี่ยวกับ ชีวิต และการเดินทาง
url: ""
baseurl: ""
lang: th-TH
timezone: Asia/Bangkok
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
future: false
collections:
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Greerati Santitamchai
  - scope:
      path: ""
      type: projects
    values:
      layout: project
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
